name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/flask-hello-world:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask-hello-world:latest

    - name: Deploy to Kubernetes (no kubeconfig)
      run: |
        kubectl \
          --server=${{ secrets.K8S_API_URL }} \
          --token=${{ secrets.K8S_TOKEN }} \
          --certificate-authority=<(echo "${{ secrets.K8S_CA_CRT }}") \
          apply -f deployment.yaml

       kubectl \
         --server=${{ secrets.K8S_API_URL }} \
         --token=${{ secrets.K8S_TOKEN }} \
         --certificate-authority=<(echo "${{ secrets.K8S_CA_CRT }}") \
         apply -f service.yaml
