name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/flask-hello-world:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask-hello-world:latest

    - name: Deploy to Kubernetes
      run: |
        # Decode the Kubernetes CA certificate to a temporary file
        echo "${{ secrets.K8S_CA_CRT }}" | base64 --decode > k8s-ca.crt

        # Apply Deployment
        kubectl --server=${{ secrets.K8S_API_URL }} \
                --token=${{ secrets.K8S_TOKEN }} \
                --certificate-authority=k8s-ca.crt \
                apply -f deployment.yaml

        # Apply Service
        kubectl --server=${{ secrets.K8S_API_URL }} \
                --token=${{ secrets.K8S_TOKEN }} \
                --certificate-authority=k8s-ca.crt \
                apply -f service.yaml
