name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/flask-hello-world:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask-hello-world:latest

    - name: Setup kubectl
      uses: deliverybot/kubectl-action@v1
      with:
       version: 'v1.27.0'
       server: ${{ secrets.K8S_API_URL }}
       token: ${{ secrets.K8S_TOKEN }}
       ca: ${{ secrets.K8S_CA_CRT }}

   - name: Deploy manifests
     run: |
      kubectl apply -f deployment.yaml
      kubectl apply -f service.yaml
